name: "Semgrep Scan"
description: "Run Semgrep and add results to GitHub Action summary"
inputs:
  config:
    description: "Semgrep config (default: p/ci)"
    default: "p/ci"
runs:
  using: "composite"
  steps:
    - run: pip install semgrep
      shell: bash

    - run: |
        semgrep --config "${{ inputs.config }}" --json > semgrep.json || true

        echo "## ðŸ” Semgrep Report" >> $GITHUB_STEP_SUMMARY

        count=$(jq '.results | length' semgrep.json)
        echo "**$count findings**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "$count" -gt 0 ]; then
          # Collapsible details block
          echo "<details><summary>Full Report ($count findings)</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Table header
          echo "| Rule | File | Start Line | Message |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|------------|---------|" >> $GITHUB_STEP_SUMMARY

          # Table rows
          jq -r '.results[] | 
            "| \(.check_id) | \(.path) | \(.start.line) | \(.extra.message)"' \
            semgrep.json >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
        else
          echo "âœ… No findings detected." >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
