name: "Gitleaks Scan"
description: "Run Gitleaks secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --source . --report-format json --report-path gitleaks.json

    - run: |
        echo "## 🔑 Gitleaks Report" >> $GITHUB_STEP_SUMMARY
        secrets=$(jq length gitleaks.json)
        echo "$secrets secrets found" >> $GITHUB_STEP_SUMMARY
      shell: bash
