name: "Gitleaks Scan"
description: "Run Gitleaks secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - name: Verify gitleaks/gitleaks-action version
      run: |
        git ls-remote https://github.com/gitleaks/gitleaks-action refs/tags/v2.3.9 | grep ff98106e4c7b2bc287b24eaf42907196329070c7
      shell: bash
      
    - uses: gitleaks/gitleaks-action@v2.3.9
      with:
        args: detect --source . --report-format json --report-path gitleaks.json

    - run: |
        echo "## 🔑 Gitleaks Report" >> $GITHUB_STEP_SUMMARY
        secrets=$(jq length gitleaks.json)
        echo "$secrets secrets found" >> $GITHUB_STEP_SUMMARY
      shell: bash
