name: "NuGet Security Report"
description: "Restore .NET projects and report vulnerable NuGet packages"
inputs:
  dotnet-version:
    description: "The .NET version to use"
    default: "8.0.x"

  project-path:
    description: 'Path to scan for .csproj files'
    required: false
    default: './'


runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore projects and capture warnings
      shell: bash
      run: |
        echo "## 🛡 NuGet Vulnerability Report" >> $GITHUB_STEP_SUMMARY

        all_findings=""

        for proj in $projects; do
            # Capture vulnerable packages
            vuln_output=$(dotnet list "$proj" package --vulnerable 2>&1 || true)

            # Extract relevant lines: skip headers
            vuln_lines=$(echo "$vuln_output" | tail -n +7)

            while IFS= read -r line; do
                # line example: "> RestSharp            111.4.0     111.4.0    Moderate   https://github.com/advisories/GHSA-4rr6-2v9v-wcpc"
                pkg=$(echo "$line" | awk '{print $2}')
                version=$(echo "$line" | awk '{print $3}')
                severity=$(echo "$line" | awk '{print $5}')
                advisory=$(echo "$line" | awk '{print $6}')
                title="$pkg: Known NuGet vulnerability"

                all_findings+="$severity|$pkg|$version|$advisory|$title"$'\n'
            done <<< "$vuln_lines"
        done

        if [ -z "$all_findings" ]; then
            echo "✅ No vulnerable packages detected." >> $GITHUB_STEP_SUMMARY
        else
            echo "**$(echo "$all_findings" | wc -l) vulnerabilities found**" >> $GITHUB_STEP_SUMMARY
            echo "<details><summary>Full Report ($(echo "$all_findings" | wc -l) findings)</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Severity | Package | Version | Vulnerability ID | Title |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|---------|---------|-----------------|-------|" >> $GITHUB_STEP_SUMMARY

            # Sort by severity: CRITICAL > HIGH > MODERATE > LOW > NOTE
            echo "$all_findings" | sort -t'|' -k1,1r | while IFS='|' read -r sev pkg ver adv title; do
                echo "| $sev | $pkg | $ver | $adv | $title |" >> $GITHUB_STEP_SUMMARY
            done

            echo "</details>" >> $GITHUB_STEP_SUMMARY
        fi
