name: "TruffleHog Scan"
description: "Run TruffleHog secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - name: Run TruffleHog Scan
      run: |
        # Scanning GitHub Repo where action is run and looking for verified keys (no false positives)
        # TruffleHog will show error code 183 whenever a potential secret is found
        docker run --rm -v "$PWD":/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest \
        git file:///tmp \
        --results=verified,unknown \
        --json > trufflehog.json || true  

      shell: bash
        
      
    - name: Process Results
      run: |
       echo "## 🐗 TruffleHog Report" >> $GITHUB_STEP_SUMMARY

        if [ -s trufflehog.json ]; then
          count=$(jq -c '. | length' trufflehog.json 2>/dev/null || jq -s 'length' trufflehog.json)
          echo "**$count potential secrets found**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$count" -gt 0 ]; then
            echo "| Detector | File | Line | Description |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|------|------|-------------|" >> $GITHUB_STEP_SUMMARY

            jq -r '
              .[] | 
              select(.DetectorName != null) |
              "| \(.DetectorName) | \(.SourceMetadata.Data.Git.file) | \(.SourceMetadata.Data.Git.line) | \(.DetectorDescription)"' \
              trufflehog.json >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No secrets detected." >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "⚠️ Scan completed but no results file found" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
