name: "TruffleHog Scan"
description: "Run TruffleHog secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - name: Run TruffleHog Scan
      run: |
        # Scanning GitHub Repo where action is run and looking for verified keys (no false positives)
        # TruffleHog will show error code 183 whenever a potential secret is found
        # Running version 3.95.2 (sha256:49d1c4fbbc580aac487ac7cb0517bb085826bd352d7578d62bb4c0c6b7205075) - Checked on 2026-04-24 @ https://hub.docker.com/r/trufflesecurity/trufflehog
        docker run --rm -v "$PWD":/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog@sha256:49d1c4fbbc580aac487ac7cb0517bb085826bd352d7578d62bb4c0c6b7205075 \
        git file:///tmp \
        --results=verified,unknown \
        --json > trufflehog.json || true  

      shell: bash
        
      
    - name: Process Results
      run: |
        echo "## 🐗 TruffleHog Report" >> $GITHUB_STEP_SUMMARY

        # Filter only actual secret objects (ignore logs)
        jq -c 'select(.DetectorName != null)' trufflehog.json | jq -s '.' > trufflehog_secrets.json

        if [ -s trufflehog_secrets.json ]; then
          count=$(jq '. | length' trufflehog_secrets.json)
          echo "**$count potential secrets found**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$count" -gt 0 ]; then
            echo "<details><summary>Full Report ($count findings)</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY

            # Table header
            echo "| Detector | File | Line | Description |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|------|------|-------------|" >> $GITHUB_STEP_SUMMARY

            # Table rows with clickable file links
            jq -r --arg repo "$GITHUB_REPOSITORY" --arg ref "$GITHUB_REF_NAME" '.[] |
              "| \(.DetectorName) | [\(.SourceMetadata.Data.Git.file)](https://github.com/\($repo)/blob/\($ref)/\(.SourceMetadata.Data.Git.file)#L\(.SourceMetadata.Data.Git.line)) | \(.SourceMetadata.Data.Git.line) | \(.DetectorDescription)"' \
              trufflehog_secrets.json >> $GITHUB_STEP_SUMMARY

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ No secrets detected." >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "⚠️ Scan completed but no secrets found." >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
