name: "TruffleHog Scan"
description: "Run TruffleHog secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - name: Run TruffleHog Scan
      run: |
        # Scanning GitHub Repo where action is run and looking for verified keys (no false positives)
        # TruffleHog will show error code 183 whenever a potential secret is found
        docker run --rm -v "$PWD":/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest \
        git file:///tmp \
        --results=verified,unknown \
        --json > trufflehog.json || true  

      shell: bash
        
      
    - name: Process Results
      run: |
        echo "## ðŸ— TruffleHog Report" >> $GITHUB_STEP_SUMMARY

        if [ -s trufflehog.json ]; then
          # Loop through each JSON object
          jq -c '.' trufflehog.json | while read -r secret; do
            has_detector=$(echo "$secret" | jq 'has("DetectorName") and .DetectorName != null')
            if [ "$has_detector" = "true" ]; then
              echo "### Detected Secret:" >> $GITHUB_STEP_SUMMARY
              echo "$secret" | jq -r '"- **Raw:** \(.Raw) | **File:** \(.SourceMetadata.Data.Git.file) (line: \(.SourceMetadata.Data.Git.line)) | **Description:** \(.DetectorDescription)"' >> $GITHUB_STEP_SUMMARY
            fi
          done

        else
          echo "âš ï¸ Scan completed but no results file found" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
