name: "TruffleHog Scan"
description: "Run TruffleHog secret scanner and add results to summary"
runs:
  using: "composite"
  steps:
    - name: Run TruffleHog Scan
      run: |
        # Scanning GitHub Repo where action is run and looking for verified keys (no false positives)
        # TruffleHog will show error code 183 whenever a potential secret is found
        docker run --rm -v "$PWD":/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest \
        git file:///tmp \
        --results=verified,unknown \
        --json > trufflehog.json || true  

      shell: bash
        
      
    - name: Process Results
      run: |
       echo "## ðŸ— TruffleHog Report" >> $GITHUB_STEP_SUMMARY

        # Filter only actual secret objects (ignore logs)
        jq -c 'select(.DetectorName != null)' trufflehog.json | jq -s '.' > trufflehog_secrets.json

        if [ -s trufflehog_secrets.json ]; then
          count=$(jq '. | length' trufflehog_secrets.json)
          echo "**$count potential secrets found**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$count" -gt 0 ]; then
            # Table header
            echo "| Detector | File | Line | Description |" >> $GITHUB_STEP_SUMMARY
            echo "|----------|------|------|-------------|" >> $GITHUB_STEP_SUMMARY

            # Table rows
            jq -r '.[] | 
              "| \(.DetectorName) | \(.SourceMetadata.Data.Git.file) | \(.SourceMetadata.Data.Git.line) | \(.DetectorDescription)"' \
              trufflehog_secrets.json >> $GITHUB_STEP_SUMMARY
          else
            echo "âœ… No secrets detected." >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "âš ï¸ Scan completed but no secrets found." >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
